'update' command: Use either curl or wget, exit if both are missing

diff --git a/bin/update b/bin/update
--- a/bin/update
+++ b/bin/update
@@ -121,13 +121,48 @@ function list_updates() {
   done
 }
 
+function download() {
+  if exists curl; then
+    curl --location --progress-bar "$1" --output "$2"
+  elif exists wget; then
+    wget --quiet --no-verbose --show-progress "$1" --output-document "$2"
+  else
+    echo -e "${RED}Error!${NC}"
+    echo -e "You need ${BLUE}curl${NC} or ${BLUE}wget${NC} to use ${BLUE}update${NC}."
+    exit 1
+  fi
+}
+
+function get_json_data() {
+  local json_data
+  if exists curl; then
+    json_data=$(
+      curl \
+        --silent \
+        --header "$2" \
+        "$1"
+    )
+  elif exists wget; then
+    json_data=$(
+      wget \
+        --quiet \
+        --no-verbose \
+        --header "$2" \
+        --output-document - \
+        "$1"
+    )
+  else
+    echo -e "${RED}Error!${NC}"
+    echo -e "You need ${BLUE}curl${NC} or ${BLUE}wget${NC} to use ${BLUE}update${NC}."
+    exit 1
+  fi
+  echo "$json_data"
+}
+
 function get_github_version() {
   local latest_version
   latest_version=$(
-    curl \
-      --silent \
-      --header "Accept: application/vnd.github.v3+json" \
-      "https://api.github.com/repos/$1/releases/latest" |
+    get_json_data "https://api.github.com/repos/$1/releases/latest" "Accept: application/vnd.github.v3+json" |
     grep '"tag_name":' |
     sed -E 's/.*"([^"]+)".*/\1/'
   )
@@ -138,10 +173,7 @@ function get_tildegit_version() {
   # This needs jq because Gitea’s API doesn’t return JSON with linebreaks
   local latest_version
   latest_version=$(
-    curl \
-      --silent \
-      --header "Content-Type: application/json" \
-      "https://tildegit.org/api/v1/repos/$1/releases/?page=1&limit=1" |
+    get_json_data "https://tildegit.org/api/v1/repos/$1/releases/?page=1&limit=1" "Content-Type: application/json" |
     jq . |
     grep '"tag_name":' |
     sed -E 's/.*"([^"]+)".*/\1/'
@@ -153,10 +185,7 @@ function get_version_from_json() {
   local version_key=${2:-"version"}
   local latest_version
   latest_version=$(
-    curl \
-      --silent \
-      --header "Accept: application/json" \
-      "$1" |
+    get_json_data "$1" "Content-Type: application/json" |
     grep '"'"$version_key"'":' |
     sed -E 's/.*"([^"]+)".*/\1/'
   )
@@ -208,7 +237,7 @@ function update_bat() {
     filename="bat-$latest_version-x86_64-unknown-linux-gnu.tar.gz"
   fi
   echo -e "Downloading ${BLUE}bat${NC} $latest_version ($filename)"
-  curl -L https://github.com/"$repo"/releases/download/"$latest_version"/"$filename" -o ~/tmp/bat.tgz
+  download https://github.com/"$repo"/releases/download/"$latest_version"/"$filename" "$HOME/tmp/bat.tgz"
   # --strip 1 makes sure we only get the files and not an extra container directory
   tar xzf ~/tmp/bat.tgz --directory ~/tmp --strip 1
   mv ~/tmp/bat ~/bin/
@@ -245,7 +274,7 @@ function update_bombadillo() {
     filename="bombadillo-""$latest_version""_linux_amd64.zip"
   fi
   echo -e "Downloading ${BLUE}bombadillo${NC} $latest_version ($filename)"
-  curl -L https://bombadillo.colorfield.space/binaries/"$filename" -o ~/tmp/bombadillo.zip
+  download https://bombadillo.colorfield.space/binaries/"$filename" "$HOME/tmp/bombadillo.zip"
   unzip -qqo ~/tmp/bombadillo.zip -d ~/tmp
   mv ~/tmp/bombadillo ~/bin/
   mv ~/tmp/bombadillo.1 ~/bin/
@@ -291,7 +320,7 @@ function update_delta() {
     filename="delta-$latest_version-x86_64-unknown-linux-gnu.tar.gz"
   fi
   echo -e "Downloading ${BLUE}delta${NC} $latest_version ($filename)"
-  curl -L https://github.com/"$repo"/releases/download/"$latest_version"/"$filename" -o ~/tmp/delta.tgz
+  download https://github.com/"$repo"/releases/download/"$latest_version"/"$filename" "$HOME/tmp/delta.tgz"
   # --strip 1 makes sure we only get the files and not an extra container directory
   tar xzf ~/tmp/delta.tgz --directory ~/tmp --strip 1
   mv ~/tmp/delta ~/bin/
@@ -324,7 +353,7 @@ function update_fzf() {
       filename="fzf-$latest_version-darwin_arm64.zip"
     fi
     echo -e "Downloading ${BLUE}fzf${NC} $latest_version ($filename)"
-    curl -L https://github.com/"$repo"/releases/download/"$latest_version"/"$filename" -o ~/tmp/fzf.zip
+    download https://github.com/"$repo"/releases/download/"$latest_version"/"$filename" "$HOME/tmp/fzf.zip"
     unzip -qqo ~/tmp/fzf.zip -d ~/tmp
   elif [[ "$os" = "termux" ]]; then
     echo -e "Please run ${BROWN}apt upgrade fzf${NC} instead."
@@ -336,7 +365,7 @@ function update_fzf() {
       filename="fzf-$latest_version-linux_amd64.tar.gz"
     fi
     echo -e "Downloading ${BLUE}fzf${NC} $latest_version ($filename)"
-    curl -L https://github.com/"$repo"/releases/download/"$latest_version"/"$filename" -o ~/tmp/fzf.tgz
+    download https://github.com/"$repo"/releases/download/"$latest_version"/"$filename" "$HOME/tmp/fzf.tgz"
     tar xzf ~/tmp/fzf.tgz --directory ~/tmp # --strip 1 # Not needed?
   fi
   mv ~/tmp/fzf ~/bin/
@@ -375,7 +404,7 @@ function update_grit() {
     filename="grit_${latest_version}_linux_amd64.tar.gz"
   fi
   echo -e "Downloading ${BLUE}grit${NC} $latest_version ($filename)"
-  curl -L https://github.com/"$repo"/releases/download/"$latest_version"/"$filename" -o ~/tmp/grit.tgz
+  download https://github.com/"$repo"/releases/download/"$latest_version"/"$filename" "$HOME/tmp/grit.tgz"
   tar xzf ~/tmp/grit.tgz --directory ~/tmp --strip 1
   mv ~/tmp/grit ~/bin/
 }
@@ -411,13 +440,13 @@ function update_gron() {
   elif [[ "$os" = "linux" ]]; then
     filename="gron-linux-amd64-$clean_version.tgz"
   fi
-  curl -L https://github.com/"$repo"/releases/download/"$latest_version"/"$filename" -o ~/tmp/gron.tgz
+  echo -e "Downloading ${BLUE}gron${NC} $latest_version ($filename)"
+  download https://github.com/"$repo"/releases/download/"$latest_version"/"$filename" "$HOME/tmp/gron.tgz"
   tar xzf ~/tmp/gron.tgz --directory ~/tmp
   mv ~/tmp/gron ~/bin/
 }
 
 function update_h2c() {
-  # https://github.com/curl/h2c/raw/1.0/h2c
   local repo="curl/h2c"
   local latest_version
   latest_version=$(get_github_version "$repo")
@@ -433,7 +462,7 @@ function update_h2c() {
 
   # h2c has no version command, proceed with install
   echo -e "Downloading ${BLUE}h2c${NC} $latest_version"
-  curl -L https://github.com/"$repo"/raw/"$latest_version"/h2c -o ~/bin/h2c
+  download https://github.com/"$repo"/raw/"$latest_version"/h2c "$HOME/bin/h2c"
   chmod u+x ~/bin/h2c
 }
 
@@ -470,7 +499,7 @@ function update_micro() {
     filename="micro-$clean_version-linux64.tar.gz"
   fi
   echo -e "Downloading ${BLUE}micro${NC} $latest_version ($filename)"
-  curl -L https://github.com/"$repo"/releases/download/"$latest_version"/"$filename" -o ~/tmp/micro.tgz
+  download https://github.com/"$repo"/releases/download/"$latest_version"/"$filename" "$HOME/tmp/micro.tgz"
   tar xzf ~/tmp/micro.tgz --directory ~/tmp --strip 1
   mv ~/tmp/micro ~/bin/
 }
@@ -494,7 +523,7 @@ function update_nb() {
     get_confirmation "$local_version" "$latest_version"
   fi
 
-  curl -L https://raw.github.com/xwmx/nb/master/nb -o ~/tmp/nb
+  download https://raw.github.com/xwmx/nb/master/nb "$HOME/tmp/nb"
   mv ~/tmp/nb ~/bin/
   chmod u+x ~/bin/nb
   nb completions install --download
@@ -533,7 +562,7 @@ function update_starship() {
     filename="starship-x86_64-unknown-linux-gnu.tar.gz"
   fi
   echo -e "Downloading ${BLUE}starship${NC} $latest_version ($filename)"
-  curl -L https://github.com/"$repo"/releases/download/"$latest_version"/"$filename" -o ~/tmp/starship.tgz
+  download https://github.com/"$repo"/releases/download/"$latest_version"/"$filename" "$HOME/tmp/starship.tgz"
   tar xzf ~/tmp/starship.tgz --directory ~/tmp
   mv ~/tmp/starship ~/bin/
 }
@@ -558,7 +587,7 @@ function update_svtplay-dl() {
   fi
 
   echo -e "Downloading latest version of ${BLUE}svtplay-dl${NC}"
-  wget https://svtplay-dl.se/download/latest/svtplay-dl -O ~/bin/svtplay-dl
+  download https://svtplay-dl.se/download/latest/svtplay-dl "$HOME/bin/svtplay-dl"
   chmod u+x ~/bin/svtplay-dl
 }
 
@@ -572,7 +601,7 @@ function update_wp-cli() {
   fi
 
   echo -e "Downloading latest version of ${BLUE}wp-cli${NC}"
-  wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -O ~/bin/wp
+  download https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar "$HOME/bin/wp"
   chmod u+x ~/bin/wp
 }
 
@@ -596,7 +625,7 @@ function update_youtube-dl() {
   fi
 
   echo -e "Downloading latest version of ${BLUE}youtube-dl${NC}"
-  wget https://yt-dl.org/downloads/latest/youtube-dl -O ~/bin/youtube-dl
+  download https://yt-dl.org/downloads/latest/youtube-dl "$HOME/bin/youtube-dl"
   chmod u+x ~/bin/youtube-dl
 }
 
@@ -629,7 +658,7 @@ function update_zola() {
     filename="zola-$latest_version-x86_64-unknown-linux-gnu.tar.gz"
   fi
   echo -e "Downloading ${BLUE}zola${NC} $latest_version ($filename)"
-  curl -L https://github.com/"$repo"/releases/download/"$latest_version"/"$filename" -o ~/tmp/zola.tgz
+  download https://github.com/"$repo"/releases/download/"$latest_version"/"$filename" "$HOME/tmp/zola.tgz"
   tar xzf ~/tmp/zola.tgz --directory ~/tmp
   mv ~/tmp/zola ~/bin/
 }
