For safekeeping

diff --git a/does b/does
--- a/does
+++ b/does
@@ -44,7 +44,6 @@ function _backup() {
 }
 
 function _sync() {
-  #shopt -s expand_aliases
   if [ "$1" == "--force" -o "$1" == "-f" ]; then
     doIt
   else
@@ -57,13 +56,13 @@ function _sync() {
       return
     fi
   fi
-  echo -e "\nFiles copied. Run ${BOLD}${YELLOW}source $HOME/.bash_profile${RESET} to reload."
+  declare -f -F r > /dev/null && r || echo -e "Could not reload profile. Run ${BOLD}${YELLOW}source $HOME/.bash_profile${RESET} manually."
 }
 
 # https://github.com/mathiasbynens/dotfiles/blob/master/bootstrap.sh
 function doIt() {
-  rsync --exclude ".git/" --exclude "bak/" --exclude ".DS_Store" --exclude "dfiles" \
-    --exclude "help.*" --exclude ".gitignore" \
+  rsync --exclude ".git/" --exclude "bak/" --exclude ".DS_Store" --exclude "does" \
+    --exclude "help.*" --exclude ".gitignore" --exclude ".extras" \
     --exclude "README.md" --exclude "LICENSE-MIT.txt" -av --no-perms . ~
 }
 
@@ -86,16 +85,21 @@ case "$1" in
     _backup
   ;;
 
+  install)
+    git clone https://github.com/spitlo/dotfiles.git && _sync $2
+  ;;
+
   help)
     _help
   ;;
   
   *)
-    echo -e "USAGE: dfiles [ sync | copy | reset | backup | help ]"
+    echo -e "USAGE: ${BOLD}. do${RESET} [ sync | copy | reset | backup | help ]"
     echo -e "\t${UNDERLINE}sync${RESET} pulls from git and copies the files."
     echo -e "\t${UNDERLINE}copy${RESET} only copies the files."
     echo -e "\t${UNDERLINE}reset${RESET} will do a hard reset from repo. Warning! Will overwrite all local files."
     echo -e "\t${UNDERLINE}backup${RESET} saves all .files from  to ~ to ~/dotfiles/bak."
+    echo -e "\t${UNDERLINE}install${RESET} clones my dotfiles repo from GitHub and copies the files."
     echo -e "\t${UNDERLINE}help${RESET} prints a partial list of commands."
 esac
 
